Zjr/create pings
mojotech/situation-room pull request #37
Opened 2022-05-17 18:45 UTC by zach-bob

[Per this card](https://github.com/mojotech/situation-room/projects/1#card-82057978) and contrary to this branch's name - this PR implements the first pass for site_checks in relation to site. Please do not merge this PR until [PR 36](https://github.com/mojotech/situation-room/pull/36) is merged.

2022-05-19 19:04 UTC, cpjolicoeur requested changes

2022-05-19 19:04 UTC, cpjolicoeur commented on lib/situation_room/sites/site_controller.ex
> +  forward("/:id/checks", to: SituationRoom.Site.Check.Controller)
I think this change should be included in the commit where the Controller is added.  Or the adding of the controller should move forward to this commit here.  There is not value in having the controller introduced but not consumed.  That breaks the atomic nature a bit.

2022-05-19 19:04 UTC, cpjolicoeur commented on lib/situation_room/site_checks/site_check_controller.ex
> +  )
What are these parsers here for?  We don't need any parsing as we only have a GET endpoint?

2022-05-19 19:04 UTC, cpjolicoeur commented on priv/repo/migrations/20220513131026_create_pings.exs
> +      add :site_id, references(:sites)
This also cannot be null

2022-05-20 12:55 UTC, zach-bob commented on lib/situation_room/site_checks/site_check.ex
> +  @derive {Jason.Encoder, except: [:__meta__]}
I thought that as well, but but when using `@derive Jason.Encoder`, I observe this error:
```
[error] #PID<0.474.0> running SituationRoom.Router (connection #PID<0.473.0>, stream id 1) terminated
Server: localhost:4001 (http)
Request: GET /sites/
** (exit) an exception was raised:
    ** (RuntimeError) cannot encode metadata from the :__meta__ field for SituationRoom.Site to JSON. This metadata is used internally by Ecto and should never be exposed externally.

You can either map the schemas to remove the :__meta__ field before encoding to JSON, or explicit list the JSON fields in your schema:

    defmodule SituationRoom.Site do
      # ...

      @derive {Jason.Encoder, only: [:name, :title, ...]}
      schema ... do
```

2022-05-20 17:07 UTC, cpjolicoeur approved these changes

2022-05-20 17:07 UTC, merged